server {
    listen 80;
    server_name _;

    # Sirve la aplicación React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Inverso hacia el backend de Despachos (Con limpieza de barra final)
    location /api/v1/despachos {
        rewrite ^/api/v1/despachos/$ /api/v1/despachos break; # ⬅️ Quita la barra final si existe
        proxy_pass http://back-despacho-svc:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy Inverso hacia el backend de Ventas (Con limpieza de barra final)
    location /api/v1/ventas {
        rewrite ^/api/v1/ventas/$ /api/v1/ventas break;       # ⬅️ Quita la barra final si existe
        proxy_pass http://back-ventas-svc:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}