apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_ENDPOINT: "mysql-svc"       # Reemplaza la IP 10.0.5.49 para usar el servicio interno
  DB_USERNAME: "root"            # Texto plano real del usuario administrador
  DB_PASSWORD: "admin123"        # Texto plano real de la contraseña de tu MySQL interno
  DB_NAME: "innovatech_db"       # Nombre del esquema de la base de datos