apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_ENDPOINT: "mysql-svc"       # ⬅️ Cambiado para apuntar al MySQL interno del clúster
  DB_USERNAME: "root"            # ⬅️ El usuario administrador del contenedor
  DB_PASSWORD: "admin123"        # ⬅️ La contraseña del contenedor
  DB_NAME: "tienda_perritos"     # ⬅️ Tu base de datos actual